Sang4_Tuan3_2011064477_PhamVanThanh/Controllers/SachController.cs
using Sang4_Tuan3_2011064477_PhamVanThanh.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sang4_Tuan3_2011064477_PhamVanThanh.Controllers
{
    public class SachController : Controller
    {
        MyDataDataContext data = new MyDataDataContext();
        // GET: Sach
        public ActionResult Index()
        {
            var all_Sach = from aa in data.Saches select aa;
            return View(all_Sach);
        }
        public ActionResult Detail(int id)
        {
            var D_sach = data.Saches.Where(m => m.masach == id).First();
            return View(D_sach);
        }
        //-------------Create-------------------
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection, Sach s)
        {
            var ten = collection["tensach"];
            if (string.IsNullOrEmpty(ten))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                s.tensach = ten;
                data.Saches.InsertOnSubmit(s);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Create();
        }
        public ActionResult Edit(int id)
        {
            var E_category = data.TheLoais.First(m => m.maloai == id);
            return View(E_category);
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var sach = data.Saches.First(m => m.masach == id);
            var E_tensach = collection["tensach"];
            sach.masach = id;
            if (string.IsNullOrEmpty(E_tensach))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                sach.tensach = E_tensach;
                UpdateModel(sach);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Edit(id);
        }

        public ActionResult Delete(int id)
        {
            var D_sach = data.Saches.First(m => m.masach == id);
            return View(D_sach);
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var D_sach = data.Saches.Where(m => m.masach == id).First();
            data.Saches.DeleteOnSubmit(D_sach);
            data.SubmitChanges();
            return RedirectToAction("Index");
        }
    }
}

Sang4_Tuan3_2011064477_PhamVanThanh/Views/Sach/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Create</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
<fieldset>
    <p>
        Mã loại:
        @Html.TextBox("maloai")<font color="red">@ViewData["Error"]</font>
    </p>
    <p>
        Tên sách:
        @Html.TextBox("tensach")<font color="red">@ViewData["Error"]</font>
    </p>
    <p>
        Hình :
        @Html.TextBox("hinh")<font color="red">@ViewData["Error"]</font>
    </p>
    <p>
        <input type="submit" value="Create" />
    </p>
</fieldset>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Sang4_Tuan3_2011064477_PhamVanThanh/Views/Sach/Delete.cshtml
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Delete</h2>
<fieldset>
    <div class="display-label">Mã sách: @Html.Encode(Model.masach)</div>
    <div class="display-lable">Mã loại: @Html.Encode(Model.maloai)</div>
    <div class="display-lable">Tên sách: @Html.Encode(Model.tensach)</div>
    <div class="display-lable">Hình: @Html.Encode(Model.hinh)</div>
</fieldset>
@using (Html.BeginForm())
{
    <p>
        <input type="submit" value="Delete" />
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Sang4_Tuan3_2011064477_PhamVanThanh/Views/Sach/Detail.cshtml
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detail</h2>
<fieldset>
    <div class="display-label">Mã sách: @Model.masach</div>
    <div class="display-label">Mã loại: @Model.maloai</div>
    <div class="display-label">Tên loại: @Model.tensach</div>
    <div class="display-label">Hình: @Model.hinh </div>
</fieldset>
@using (Html.BeginForm())
{
    <p>
        @Html.ActionLink("Delete", "Delete", new { id = Model.maloai }) |
        @Html.ActionLink("Edit", "Edit", new { id = Model.maloai }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Sang4_Tuan3_2011064477_PhamVanThanh/Views/Sach/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Edit</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
<fieldset>
    <div class="editor-field">
        Tên sách:
        @Html.TextBox("tensach");
        @ViewData["Error"]
    </div>
    <div class="editor-field">
        Hình:
        @Html.TextBox("hinh");
        @ViewData["Error"]
    </div>
    <p>
        <input type="submit" value="Save" />
    </p>
</fieldset>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Sang4_Tuan3_2011064477_PhamVanThanh/Views/Sach/Index.cshtml
@model IEnumerable<Sang4_Tuan3_2011064477_PhamVanThanh.Models.Sach>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SACH</h2>

<table border="1px">
    <tr>
        <th>Mã sách</th>
        <th>Mã loại</th>
        <th>Tên sách</th>
        <th>Hình</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.masach</td>
            <td>@item.maloai</td>
            <td>@item.tensach</td>
            <td>@item.hinh</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.masach }) |
                @Html.ActionLink("Detail", "Detail", new { id = item.masach }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.masach })
            </td>
        </tr>
    }
</table>
@Html.ActionLink("Create", "Create", "Sach")